### ISSUE TITLE
关于git操作

### ISSUE THREAD

**Issue by misshy** [Coding/WebIDE-Backend#11]
请问coding.net后台是如何对接 为每个用户生成ssh key  并根据ssh key各自为每个用户创建workspace。后台难道根据用户个数搭建了不同的虚拟机？还是后台只有只有一台服务器，没有虚拟机，您把所有的ssh key都存在数据库，根据ssh key（有用户标志）来确认当前git为哪个用户服务？还是其他方案？

**Comment by vangie** [comment]
开源版本没有包含多租户的功能。平台版本的后台是基于 docker 做的，不是虚拟机技术，平台版是一个分布式系统，有很多台服务器。如果有与多租户相关的业务需要可以留意一下企业版，https://ide.coding.net/enterprise
