### ISSUE TITLE
编译不了呀

### ISSUE THREAD

**Issue by Neo110** [Coding/WebIDE-Backend#12]
[INFO] ------------------------------------------------------------------------
[INFO] Building Coding IDE Backend 0.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) > test-compile @ backend >>>
[WARNING] The POM for net.coding.ide:frontend:jar:1.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.790 s
[INFO] Finished at: 2016-11-14T21:11:11+08:00
[INFO] Final Memory: 17M/227M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project backend: Could not resolve dependencies for project net.coding.ide:backend:jar:0.1.1-SNAPSHOT: Failure to find net.coding.ide:frontend:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by tanhe123** [comment]
从错误信息来看，是没有执行 build 操作

```
./ide.sh build
```

**Comment by Neo110** [comment]
ide.sh  没有个脚本呀

**Comment by tanhe123** [comment]
参考这里：https://github.com/Coding/WebIDE
