### ISSUE TITLE
本地编译运行，主页显示Whitelabel Error Page  /没有映射 

### ISSUE THREAD

**Issue by uptonking** [Coding/WebIDE-Backend#26]
3个项目按步骤编译以后，执行mvn spring-boot:run，主页提示映射错误，控制台没有报错信息，如下图：  

![index no map error](https://uptonking.github.io/assets/issues/codingwebide/index_no_map.png)

http://localhost:8080/user 能够显示username和avatar

已检查：

- frontend正常编译，build目录文件齐全，主页有内容
- webjar项目打包前端正常，maven本地目录那里有4.9M的jar包
- backend项目配置未做任何修改

**Comment by tanhe123** [comment]
getter、setter、builder 等方法的生成，使用了 lombok 库，会在编译时自动生成

**Comment by tanhe123** [comment]
当前这个项目仅仅是一个 submodule，如果想要启动整套 WebIDE 环境，可以查看该文档： https://github.com/Coding/WebIDE/blob/master/README-zh.md

**Comment by tanhe123** [comment]
具体做法就是：

从 Coding 克隆项目：

```
从 Github 克隆项目：
git clone git@github.com:Coding/WebIDE.git

拉取子项目：
git submodule init
git submodule update

这样就会通过 git 的 submodule 机制 clone 另外 3 个 repo。

./ide.sh build   # 编译并打包前端项目
./ide.sh run     # 启动项目
```

**Comment by uptonking** [comment]
@tanhe123  这些内容我都看过了，我是3个项目分别处理的
我单项目启动前端 yarn start， 主页是有内容的
但是在backend执行就出现了问题

**Comment by tanhe123** [comment]
先试下我刚才提到的方法？

因为 ./ide.sh build 实际上就是进入到 backend 目录执行了 

```
mvn clean package -Dmaven.test.skip=true
```
如果使用 ./ide.sh 可行，而 3 个项目分别处理不行，那就说明处理的方法有问题，如果连直接使用 ./ide.sh 都不可行，可能是您机器的环境配置有些问题，我再帮您排查。

**Comment by uptonking** [comment]
```
./ide.sh build   # 编译并打包前端项目
./ide.sh run     # 启动项目
```
成功运行了，ide能够正常访问

我又试了试对于backend项目单独执行
```
mvn clean package
java -jar target/ide-backend.jar 
```
ide也是能够正常访问的 

但是单独执行`mvn spring-boot:run`依旧是Whitelabel Error Page的错误  

看来spring-boot它自己设计的通用命令还是不够完善，就像黑盒一样，以后还是mvn + java -jar对程序员透明一点
