### ISSUE TITLE
想请问一下atmosphere的term.close什么情况下会被触发？

### ISSUE THREAD

**Issue by DmuMenDuo** [Coding/WebIDE-Backend#30]
SocketIOHandler.java
![default](https://user-images.githubusercontent.com/28503073/34203733-2565b3a4-e5b7-11e7-88ad-96ef469dddb3.png)
![default](https://user-images.githubusercontent.com/28503073/34204006-062269d2-e5b8-11e7-8ed7-0a47ddb8362a.png)

前台的那个终端，点了x。我这里不会触发term.close 。我想在终端关闭的时候做一些别的事情，但是现在触发不了？

谢谢！

**Comment by tanhe123** [comment]
已创建 issue https://github.com/Coding/WebIDE/issues/326

**Comment by tanhe123** [comment]
![image](https://user-images.githubusercontent.com/4676235/34284806-b021c1aa-e70f-11e7-968a-9b1ed06a32f4.png)
点击这个关闭按钮、或者输入 exit 都会触发 term.close
