### ISSUE TITLE
Can't create the project with github

### ISSUE THREAD

**Issue by lichenhao** [Coding/WebIDE-Backend#6]
Throw an error with `org.eclipse.jgit.api.errors.TransportException: xxxxxxx: connection is closed by foreign host`

And, if I overwrite the backend with nodejs, what should I do? It's there some documents for guild.

**Comment by misshy** [comment]
`And, if I overwrite the backend with nodejs, what should I do? It's there some documents for guild.`
this is also my duty to do

**Comment by lichenhao** [comment]
@misshy I will wait for that, and thanks for the awesome project.

**Comment by tanhe123** [comment]
@lichenhao This seems to be a network problem. 
Maybe you should try again.

**Comment by lichenhao** [comment]
@tanhe123  The problem is clone project with an error SSH Key. I find out it.
