### ISSUE TITLE
Source Download failed (and some unstable)

### ISSUE THREAD

**Issue by owtotwo** [Coding/WebIDE-Backend#7]
The source link failed(maybe the result from my network environment?): http://oss.sonatype.org/content/groups/public/org/glassfish/hk2/hk2-locator/2.3.0-b05/hk2-locator-2.3.0-b05.jar
(Is it the problem of maven...?)
![image](https://cloud.githubusercontent.com/assets/13444035/18606473/e608d980-7ce3-11e6-8ea8-e2931659f709.png)

**Comment by tanhe123** [comment]
@owtotwo The jar can not be download with the link. Bu maven can download the jar with the link.  it seems something wrong on this site.

try to remove this content in pom.xml:

```
    <repositories>
        <repository>
            <id>sonatype</id>
            <name>Sonatype OSS Snapshots Repository</name>
            <url>http://oss.sonatype.org/content/groups/public</url>
        </repository>
    </repositories>
```

**Comment by owtotwo** [comment]
Thanks! It works, but ... it seems to be something wrong  with the front-end
(Does the "setting" not finish yet? and the terminal can not be folded... and some other problems exist...such as the font-size and so on.)

**Comment by hackape** [comment]
@owtotwo yeah, the frontend is undergone a heavy refactor, lota stuff being re-implemented, but we'll catch up soon. Meanwhile I suggest you check out [live demo](https://ide.coding.net/ws/?ownerName=duwan&projectName=WordPress&isTry=true) to see all the features to come.
